services:
  hello-world:
    image: ghcr.io/sikalabs/hello-world-server:v0.10.0
    networks:
      - traefik
    deploy:
      replicas: 4
    labels:
      - traefik.enable=true
      - traefik.http.services.hello-world.loadbalancer.server.port=8000
      - traefik.http.routers.hello-world.rule=Host(`${HOST:-hello-127-0-0-1.nip.io}`)

networks:
  traefik:
    name: traefik
    external: true
